#cloud-config

# Cloud-init for repo.eessi-hpc.org

hostname: repo.eessi-hpc.org

yum_repos:
    epel-release:
        baseurl: https://download.fedoraproject.org/pub/epel/$releasever/Everything/$basearch
        metalink: https://mirrors.fedoraproject.org/metalink?repo=epel-$releasever&arch=$basearch&infra=$infra&content=$contentdir
        enabled: true
        gpgcheck: true
        gpgkey: http://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8
        name: Extra Packages for Enterprise Linux 8 - Release

package_upgrade: true

packages:
  - ansible
  - awscli
  - git
  - htop
  # required for semanage
  - policycoreutils-python-utils
  - python38
  - screen
  - singularity
  - tmux
  - httpd

runcmd:
  # - curl -O -L --quiet
  - systemctl enable httpd
  - systemctl start httpd